services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pproj3.sql:/docker-entrypoint-initdb.d/pproj3.sql
      - PPROJ3-db-data:/var/lib/postgresql/data
    networks:
      - PPROJ3-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - PPROJ3-network
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - PPROJ3-network
    depends_on:
      - db
    env_file:
      - .env

volumes:
  PPROJ3-db-data:

networks:
  PPROJ3-network